# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJ4VG8HcsrxyxniBuEx2vWkGrZKvccr2
"""

import numpy as np

a = np.array([1,2,3,4,5])
b = [1,2,3,4,5]

print(a)
print(b)

a = a + 1
b = b + [1]

print(a)
print(b)